### ISSUE TITLE
caching?

### ISSUE THREAD

**Issue by laerm0** [googlefonts/gfregression#42]
Hey @m4rc1e , I am trying the live version you have on the web. I wonder if the files cache somehow because I uploaded a font, made some changes, and then uploaded again, but my changes aren't there.

Here's [the first](http://159.65.243.73/compare/4f6ccda5-3a3f-45e5-8210-773227a3fde7), here's [the second](http://159.65.243.73/compare/85a7c1cc-bd3e-4b4e-b749-91d5d268aef3).

I am going to diff the cached files and see what I can learn.

**Comment by m4rc1e** [comment]
Just ran both through diffbrowsers, They're different but not by much.

![screen shot 2018-10-31 at 19 10 48](https://user-images.githubusercontent.com/7525512/47812601-bfc7fc00-dd40-11e8-940e-9e8c75066fc9.png)

Each time you upload a set of fonts, it will create unique filenames for each one so GFR won't be caching them. Maybe it's your browser but I'm not sure of this either.

**Comment by m4rc1e** [comment]
Out of curiosity, is this an x-height delta?

**Comment by laerm0** [comment]
Yep, that's an x-height delta.

I'm looking at the other diffs now.

**Comment by laerm0** [comment]
Yep, that's an x-height delta. I dug around in my browser cache and there were some diffs there. I think you can close this as I think it's on my browser side.

PS I love how fast this new version is 😄

**Comment by m4rc1e** [comment]
@laerm0 Thanks!

The reason it's so fast is because it doesn't diff. My goal is to get fontdiffenator to render diffs, https://github.com/googlefonts/fontdiffenator/pull/29. GFR will then be used to test diff browser rendering only. However, if a user runs it locally, it will be able to do everything.

**Comment by laerm0** [comment]
Ahh, smart. 🧠
