### ISSUE TITLE
Work with unencoded glyphs?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gfregression#5]
From email,

> The tool only looks at encoded glyphs. 

I think its important to check unencoded glyphs for regressions too...

**Comment by m4rc1e** [comment]
I totally agree. It's just very very hard to do.

Since most unencoded glyphs are accessed by unicode features. I'll have to write an OT parser to access them. This will be added in the future.

**Comment by davelab6** [comment]
What about opentype.js to grab them directly?

**Comment by davelab6** [comment]
Also, evil: Micah Stupak-Hahn <micah@benthic.cc>

**Comment by davelab6** [comment]
OOPS

Also, evil: https://github.com/googlefonts/fontbakery/issues/388

**Comment by m4rc1e** [comment]
@davelab6 I do not like puas.

I will study [otLib](https://github.com/fonttools/fonttools/tree/master/Lib/fontTools/otlLib) in fontTools and see what I can do. Unfortunately, due to my other commitments, this is near the back of the queue. I agree its needed.

**Comment by m4rc1e** [comment]
Will be solved if #35 gets merged
